[Appearance]
color_scheme_path=/home/mavgone/.config/qt5ct/colors/matugen.conf
custom_palette=true
standard_dialogs=default
style=Fusion
stylesheets=/home/mavgone/.config/qt5ct/qss/matugen-style.qss

[Interface]
stylesheets=/home/mavgone/.config/qt5ct/qss/matugen-style.qss
